# Generated by Django 6.1 on 2026-09-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_pacienteviolenciadomestica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientesifilis',
            old_name='mu_notific',
            new_name='id_unidade',
        ),
    ]
