# Generated by Django 6.1 on 2026-09-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_pacientehans'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteHepatite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nu_notific', models.TextField(blank=True, null=True)),
                ('id_unidade', models.TextField(blank=True, null=True)),
                ('nm_ubs', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
