# Generated by Django 6.1 on 2026-09-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_pacienteanimaispec'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteAidsAdulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_notific', models.TextField(blank=True, null=True)),
                ('nu_notific', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteIntoxicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_notific', models.TextField(blank=True, null=True)),
                ('nu_notific', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PacienteLeish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_notific', models.TextField(blank=True, null=True)),
                ('nu_notific', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
