# Generated by Django 6.1 on 2026-09-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_pacienteaidsadulto_pacienteintoxicacao_pacienteleish'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteanimaispec',
            name='ano_notific',
            field=models.TextField(blank=True, null=True),
        ),
    ]
