# Generated by Django 6.1 on 2026-09-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_pacienteanimaispec_ano_notific'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoberturaVacinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('imunobiologico', models.TextField(max_length=100)),
                ('cobertura_percentual', models.FloatField()),
                ('meta_otima', models.FloatField(default=95.0)),
                ('data_atualizacao', models.DateField(auto_now=True)),
            ],
        ),
    ]
