# Generated by Django 6.1 on 2026-09-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_coberturavacinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coberturavacinal',
            name='imunobiologico',
            field=models.CharField(max_length=100),
        ),
    ]
