# Generated by Django 6.1 on 2026-09-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_coberturavacinal_imunobiologico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientechagas',
            name='ano_notific',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacientedengue',
            name='ano_notific',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacientehans',
            name='ano_notific',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacientehepatite',
            name='ano_notific',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacientesifilis',
            name='ano_notific',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacientetuberculose',
            name='ano_notific',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pacienteviolenciadomestica',
            name='ano_notific',
            field=models.TextField(blank=True, null=True),
        ),
    ]
